name: blur2vid
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.6.0=py310hd8f1fbe_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - ipykernel=6.20.2=pyh210e3f2_0
  - ipython=8.36.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.40=h12ee557_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=3.0.16=h5eee18b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py310h06a4308_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - pyzmq=23.0.0=py310h330234f_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tmux=3.3a=h5eee18b_1
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.0
      - accelerate==1.5.2
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - atomicwrites==1.4.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colour-science==0.4.6
      - contourpy==1.3.1
      - controlnet-aux==0.0.9
      - cycler==0.12.1
      - decorator==4.4.2
      - decord==0.6.0
      - denku==0.0.51
      - diffusers==0.32.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - einops-exts==0.0.4
      - fastapi==0.115.11
      - ffmpeg-python==0.2.0
      - ffmpy==0.5.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.22.0
      - gradio-client==1.8.0
      - groovy==0.1.2
      - h11==0.14.0
      - hf-transfer==0.1.9
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.3
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.6.1
      - jax==0.5.3
      - jaxlib==0.5.3
      - jinja2==3.1.6
      - jiter==0.9.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.4.2
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.4.2
      - openai==1.68.2
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.15.0
      - pillow==9.5.0
      - proglog==0.1.10
      - propcache==0.3.2
      - protobuf==4.25.6
      - psutil==5.9.8
      - ptflops==0.7.4
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.2
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - ruff==0.11.2
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-video==1.1.11
      - scipy==1.15.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.24.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.7
      - spaces==0.32.0
      - spandrel==0.4.1
      - starlette==0.46.1
      - sympy==1.13.1
      - tifffile==2025.3.13
      - timm==0.6.7
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - torch==2.6.0
      - torch-fidelity==0.3.0
      - torchmetrics==1.7.4
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.50.0
      - triton==3.2.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - videoio==0.3.0
      - wandb==0.19.8
      - websockets==15.0.1
      - yarl==1.20.1
      - zipp==3.21.0
